In [7]:
import cv2
import matplotlib.pyplot as plt
import numpy as np
import math

In [8]:
def show(img):
    cv2.imshow('img',img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [9]:
def gausskernel(size,sigma):
    #sigma=1.5
    gausskernel=np.zeros((size,size),np.float32)
    for i in range (size):
        for j in range (size):
            numerator=math.pow(i-1,2)+pow(j-1,2)
            gausskernel[i,j]=math.exp(-numerator/(2*math.pow(sigma,2)))/math.pow((2*math.pi*sigma**2),0.5) # 求高斯卷积
    sum=np.sum(gausskernel)   # 求和
    kernel=gausskernel/sum   # 归一化
    return kernel

In [10]:
def gaussfilter(img):
    h=img.shape[0]
    w=img.shape[1]
    img1=np.zeros((h,w),np.uint8)
    kernel=gausskernel(3,1.5)   # 计算高斯卷积核
    for i in range (1,h-1):
        for j in range (1,w-1):
            sum=0
            for k in range(-1,2):
                for l in range(-1,2):
                    sum+=img[i+k,j+l]*kernel[k+1,l+1]   # 高斯滤波
            img1[i,j]=sum
    return img1

In [11]:
kernel = gausskernel(3,1.5)
print(kernel)

[[0.09474166 0.11831801 0.09474166]
 [0.11831801 0.14776132 0.11831801]
 [0.09474166 0.11831801 0.09474166]]


In [12]:
img = np.array([[14,15,16],
              [24,25,26],
              [34,35,36]])
filtered_img1 = gaussfilter(img)
print(filtered_img1)

[[ 0  0  0]
 [ 0 25  0]
 [ 0  0  0]]
