In [1]:
import cv2
import numpy as np

#### 读入图像

In [2]:
img = cv2.imread('image\h.png')  
#img = cv2.imread('image\h.png',cv2.IMREAD_GRAYSCALE)

In [3]:
cv2.imshow('name',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
type(img)

numpy.ndarray

In [5]:
img.shape

(215, 321, 3)

In [6]:
print(img)

[[[ 74  85  41]
  [ 95 111  47]
  [ 99 115  49]
  ...
  [ 55  88  21]
  [ 48  85  21]
  [ 43  84  21]]

 [[ 84  95  47]
  [111 127  57]
  [115 131  60]
  ...
  [ 54  94  20]
  [ 44  91  20]
  [ 37  87  17]]

 [[ 92 101  53]
  [122 137  66]
  [126 141  69]
  ...
  [ 51  96  21]
  [ 39  91  21]
  [ 30  86  14]]

 ...

 [[ 31  82   9]
  [ 36 109   8]
  [ 54 120  37]
  ...
  [104 121  86]
  [102 120  83]
  [111 128  93]]

 [[ 31  83   9]
  [ 33 109   3]
  [ 43 115  16]
  ...
  [ 91 112  57]
  [ 91 111  55]
  [ 93 114  57]]

 [[ 32  81  10]
  [ 32 106   1]
  [ 35 108   3]
  ...
  [ 78 100  31]
  [ 78 101  31]
  [ 76 100  27]]]


In [7]:
img[0][0]

array([74, 85, 41], dtype=uint8)

In [8]:
img[0][1]

array([ 95, 111,  47], dtype=uint8)

In [9]:
img[1][0]

array([84, 95, 47], dtype=uint8)

#### 读入图像转换为灰度图像

In [10]:
img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

In [11]:
print(img,img.shape)

[[ 71  90  93 ...  64  62  60]
 [ 79 104 108 ...  67  64  60]
 [ 86 114 118 ...  68  64  58]
 ...
 [ 54  70  88 ... 109 107 116]
 [ 55  69  77 ...  93  92  95]
 [ 54  66  68 ...  77  77  75]] (215, 321)


In [12]:
cv2.imshow('name',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

#### 转换为黑白图像

In [13]:
ret,img = cv2.threshold(img,128,255,cv2.THRESH_BINARY)

In [14]:
cv2.imshow('name',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

#### 写图像

In [15]:
cv2.imwrite('image\h_gray.png',img)

True

## 如何用代码实现cv2.cvtColor(img,cv2.COLOR_RGB2GRAY)的功能？